services:
  - type: web
    name: turnero
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_CA_CONTENT
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        sync: false
