services:
  # El Cerebro (Backend)
  - type: web
    name: backend-valko
    env: node
    plan: free
    region: ohio
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: valko-secretos

  # La Pantalla (Frontend)
  - type: web
    name: frontend-valko
    env: static
    plan: free
    publishDir: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        fromServiceAccount: backend-valko
        fromServiceField: url

envVarGroups:
  - name: valko-secretos
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_CA_CONTENT
        sync: false
      - key: JWT_SECRET
        sync: false
